# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-16 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.TextField()),
                ('mime', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_file_revisions', to='projects.File')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('active_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_active_branch', to='projects.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('committed', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.Branch')),
                ('files', models.ManyToManyField(related_name='revisions', to='projects.File')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_revisions', to='projects.Revision')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_head_revision', to='projects.Revision'),
        ),
        migrations.AddField(
            model_name='branch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='projects.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('user', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set([('project', 'name')]),
        ),
    ]
