# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-07 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_file_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 5, 7, 20, 35, 38, 22599, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
