# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-07 22:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_change',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 7, 22, 51, 17, 413970, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
